name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'bench/**'
      - 'examples/**'
      - 'shots/**'
    branches:
    - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'bench/**'
      - 'examples/**'
      - 'shots/**'
    branches:
    - main

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    strategy:
      matrix:
        nodejs: [8, 10, 12, 14]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    # https://github.com/actions/setup-node
    - uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Test w/ Coverage
      run: npm run test:coverage

    - name: Report
      if: matrix.nodejs >= 14 && matrix.os == 'ubuntu-latest'
      run: |
        npm run test:report
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}